### ISSUE TITLE
Builds are incompatible with harfbuzz 3.0.0 (undefined symbol: hb_subset_input_set_retain_gids)

### ISSUE THREAD

**Issue by Magus-Sama** [ungoogled-software/ungoogled-chromium-archlinux#147]
Hello,

I had this issue on the Chaotic AUR build, but I upgraded to the OBS binary (without adding the repository) and I got the same issue. This happened in the middle of me browsing. It crashed the browser, and I can't reopen it or even check versions or whatnot:

`[joseph@joseph-20354 ~]$ chromium
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids`

I'm not sure what I did at all that broke this (not that I could check either because I cannot open the browser at all). I tried reinstalling this as well as harfbuzz to no avail.

Should this be filed under here or under the main repo?

Version: ungoogled-chromium-93.0.4577.82-1. Harfbuzz version (since afaik this is a harfbuzz issue): 3.0.0-1 (same for harfbuzz-icu).

EDIT: Tried a solution [here](https://bbs.archlinux.org/viewtopic.php?id=269739) and it did not work - it did not downgrade harfbuzz.

**Comment by networkException** [comment]
harfbuzz 3.0.0 is incompatible with the binary you were using, I already had a fix prepared based on https://github.com/archlinux/svntogit-packages/commit/b801b21ca112d4a4c053a8e90f0cac533d17477e locally and as harfbuzz 3 is in stable on the archlinux side now I pushed it: a7805e5f5b0994b0234011988785803c8a8f4469. You can either build the latest commit on your own machine, or wait for [OBS](https://build.opensuse.org/package/live_build_log/home:ungoogled_chromium/ungoogled-chromium-arch/Arch/x86_64) or [GitHub Actions](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/1258827236) to finish

**Comment by Magus-Sama** [comment]
Alright, thank you very much! Reserving this comment and will update it to reflect whether it works or not.

**Comment by fireglow** [comment]
Confirming, 93.0.4577.82-2 from OBS, error persists.
Installed harfbuzz packages:
```txt
harfbuzz 3.0.0-1
harfbuzz-icu 3.0.0-1
```

**Comment by networkException** [comment]
I will have to investigate further then, my local build works fine

**Comment by networkException** [comment]
Sadly the OBS build still used 2.9.1-1. I hope the GitHub Actions container is up to date, it should finish building soon

**Comment by fireglow** [comment]
OK, I'll try the GH build once it finishes.

**Comment by fireglow** [comment]
I built `93.0.4577.82-2` locally and it works 😃

**Comment by Magus-Sama** [comment]
The Github Actions build worked for me!

**Comment by networkException** [comment]
Great!

**Comment by FivePixels** [comment]
> The Github Actions build worked for me!

Which one are you referring to?

**Comment by networkException** [comment]
The binary got published as an asset of the latest release: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/93.0.4577.82-2

**Comment by Im-Beast** [comment]
After updating to `94.0.4606.54-1` it works fine

**Comment by networkException** [comment]
Yep it's fixed from 93.0.4577.82-2 onwards technically, just OBS didn't have the dependency up to date. Now that all CI builds have a working version I will close the issue
